### PR TITLE
fix: Depend on gir1.2-gstreamer-1.0, as required by screencasting

### LINKED ISSUE #45: Gnome's inbuilt screen recorder no longer working in Pop!_OS 20.10
Gnome's inbuilt screen recorder no longer working in Pop!_OS 20.10 that can be activated using the shortcut Ctrl + Shift + Alt + R.
It worked in Pop!_OS 20.04 but after upgrading to 20.10 it no longer works.

### PR DESCRIPTION
**Pull request by mmstick**
Closes #45

### CODE REVIEW

**Review by ids1024 — APPROVED** [review]
Is this an upstream issue that applies to Ubuntu as well? I [don't see](https://packages.ubuntu.com/groovy/gnome-shell) it in the dependency list of the Ubuntu package, even as a `suggests`, which presumably it should at least be if they don't intentionally disable the feature.

**Comment by mmstick** [comment]
Yep

https://salsa.debian.org/gnome-team/gnome-shell/-/commit/27aa425b2aa65684f3a466b04ff2cd3c80f1f150

**Comment by jacobgkau** [comment]
I already had `gir1.2-gstreamer-1.0` installed as a dependency of `sessioninstaller`, which is a dependency of `pop-desktop`.

Even after installing this update, the `Ctrl-Alt-Shift-R` screen recorder still doesn't work, so this should not close #45. (Desktop sharing is also missing from GNOME Control Center.)

**Comment by ids1024** [comment]
It looks like Mutter is currently compiled without support for screencasting and remote desktop: https://github.com/pop-os/mutter/pull/13

Though I'm still not seeing either function work in the VM I'm testing it in.

**Comment by ids1024** [comment]
Closing in favor of https://github.com/pop-os/gnome-shell/pull/47 which adds other necessary dependencies, and matches upstream Debian.

**Pull request closed without merging**
