### PR TITLE
Rebase groovy

### PR DESCRIPTION
**Pull request by mmstick**

### CODE REVIEW

**Review by jackpot51 — APPROVED** [review]

**Comment by jacobgkau** [comment]
This removes `gstreamer1.0-pipewire` as a dependency. After autoremoving that package, recording the screen with Ctrl-Alt-Shift-R no longer works (although I sometimes get stuck with a yellow dot in the top right of the screen that won't go away after I attempt to record.) Do we know why the dependency was removed/should we add that back?

**Comment by ids1024** [comment]
For reference, that dependency was added in https://github.com/pop-os/gnome-shell/pull/47, copying the dependencies from Debian (in contrast to what Ubuntu had). I assume we'll want all of those here still.

**Comment by jacobgkau** [comment]
Screen recording's working again after adding those dependencies back.

This update seems to fix https://github.com/pop-os/shell/issues/816, as the workspace no longer switches when I drag a window to a new in-between workspace (this matches the Focal behavior.) Pop!_Shell regression testing passed. [gnome-updates-feb23.txt](https://github.com/pop-os/gnome-shell/files/6031773/gnome-updates-feb23.txt)

My only other observation is that this is pulling in the Yaru theme as a recommends now. I don't think we want that, do we?

**Comment by mmstick** [comment]
No we don't. Removing

**Review by jacobgkau — APPROVED** [review]

**Pull request merged**
