### PR TITLE
add a testing procedure

### PR DESCRIPTION
**Pull request by n3m0-22**
This adds a testing procedure specific to gnome-shell.

### CODE REVIEW

**Comment by 13r0ck** [comment]
Should we also do a quick check if the extensions still work? DING, workspaces, dock, gestures. appindicators?

**Comment by n3m0-22** [comment]
That's a good idea. I'll work on adding some.

**Comment by jacobgkau** [comment]
While it makes sense to check more than just Pop Shell, we have had cases where GNOME Shell and/or Mutter updates caused regression that needed to be fixed in Pop Shell. It may be worth keeping Pop Shell regression testing as a checklist item in GNOME Shell's regression testing, if this list is supposed to be exhaustive.

I was surprised to see GNOME Initial Setup on here-- that's its [own application](https://github.com/pop-os/gnome-initial-setup). Have we seen GNOME Shell break G-I-S before?

**Comment by n3m0-22** [comment]
> It may be worth keeping Pop Shell regression testing as a checklist item in GNOME Shell's regression testing, if this list is supposed to be exhaustive.

I agree, but I wasn't sure if that would be too much. I don't think I would hurt to included it.

> I was surprised to see GNOME Initial Setup on here-- that's its [own application](https://github.com/pop-os/gnome-initial-setup). Have we seen GNOME Shell break G-I-S before?

As far as I know there have not been any issues. It's probably unnecessary.

**Review by 13r0ck — APPROVED** [review]
Looks good!

**Review by jacobgkau — APPROVED** [review]
Not sure if some of this is necessary to test, but can't argue with being thorough.

**Pull request merged**
