### PR TITLE
Fix conflict on upgrade in Jammy

### PR DESCRIPTION
**Pull request by mmstick**

### CODE REVIEW

**Comment by jacobgkau** [comment]
This has finished building. Should gnome-remote-desktop be able to update when this branch is added? (I'm still seeing it held back after installing the update.)

**Comment by mmstick** [comment]
I'd imagine that it'd update if this was the only source holding it back. Maybe there's something else.

**Comment by mmstick** [comment]
gnome-control-center needs to be updated too, it seems.

**Review by jacobgkau — APPROVED** [review]
Tested with https://github.com/pop-os/gnome-control-center/pull/222. Display configuration still works. Regression testing passed:
[shell-testing-for-gnome-shell-pr98-jammy.txt](https://github.com/pop-os/gnome-shell/files/8497856/shell-testing-for-gnome-shell-pr98-jammy.txt)

**Review by crawfxrd — APPROVED** [review]

**Pull request merged**
